# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170721_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='dob',
            new_name='udob',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='gender',
            new_name='ugender',
        ),
    ]
