# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170728_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
    ]
