# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170728_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidprofile',
            name='dob',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
